language: python
os: 
  - linux
python: 
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - cd tailtrim/test && pytest && cd -
  - cd tailtrim/test && ./tailtrim_test.sh && cd -
